# This workflow will install Python dependencies and run the local script
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        - cron: "0 19 * * FRI"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Prepare Selenium
              uses: nanasess/setup-chromedriver@v1.0.5
            - name: Run script
              env:
                  UST_URL: ${{ secrets.UST_URL }}
                  UST_USERNAME: ${{ secrets.UST_USERNAME }}
                  UST_PASSWORD: ${{ secrets.UST_PASSWORD }}
              run: |
                  python work.py
